tables:
  - name: hotels_zakaz
    primary:
      type: mysql
      database: intranet
      table: hotels_zakaz
      datetime_column: date
    replica:
      type: clickhouse
      database: datalensmariadb
      table: hotels_zakaz
      datetime_column: date
      final: 1
    strategy:
      row_count:  1
      lag_check: 0
    rules:
      max_row_diff: 1000
      max_lag_minutes: 60

  - name: order_stat
    primary:
      type: mysql
      database: intranet
      table: order_stat
      datetime_column: null
    replica:
      type: clickhouse
      database: datalensmariadb
      table: order_stat
      datetime_column: null
    strategy:
      row_count:  1
      lag_check: 0
    rules:
      max_row_diff: 1000
      max_lag_seconds: 60